### ISSUE TITLE
The files in result.EN/dr.CCLE/01S/

### ISSUE THREAD

**Issue by HuangStomach** [bsml320/VAEN#3]
I am trying to reproduce your result, but when I execute to `2.CCLE.S.R`, I found that there is no script to generate the file under this directory, and this file is almost identical to `1.CCLE.A.R`, what is the exact difference between these two files? And where can I generate the data files in this directory.

Thank you for answering my question in your busy schedule!

**Comment by bsml320** [comment]
2.CCLE.S.R reads the files in the folder 01S. See row 21 of this file and
1.CCLE.A.R. The files can be downloaded from
https://bioinfo.uth.edu/VAEN/result.EN/dr.CCLE/01S/

**Comment by HuangStomach** [comment]
Thanks for your answer, I see these files under the link you gave, but how are the data files generated in the 01S directory?

**Comment by bsml320** [comment]
Sorry they were accidently deleted during revision. See attached.

**Comment by bsml320** [comment]
You will also need nested_EN to run the code.

**Comment by HuangStomach** [comment]
Thanks for the heads up, I've got nested_EN from your site, but the github issue doesn't seem to support attachments, I  didn't find the file you mentioned in the issue. 

Here is a graphic representation of our conversation
<img width="927" alt="截屏2021-05-30 下午2 19 32" src="https://user-images.githubusercontent.com/8955394/120094297-13499300-c152-11eb-85c4-b90c260b7014.png">

**Comment by bsml320** [comment]
Check the code folder. They should be there.

**Comment by HuangStomach** [comment]
Saw it! Thank you for your busy schedule to solve my problem!
